module.exports = {
    formHead: {
        fontSize: 28,
        color: 'black',
        textAlign: 'center',
        fontWeight: 500,
        // backgroundColor: 'white',
    },
    formInput: {
        width: '80%',
        // height: 40,
        backgroundColor: 'white',
        borderColor: 'black',
        borderWidth: 1,
        borderRadius: 10,
        marginVertical: 10,
        paddingHorizontal: 15,
        paddingVertical: 10,
        fontSize: 18,
    },
    formbtn: {
        width: '80%',
        backgroundColor: '#a618f2',
        borderRadius: 10,
        borderColor: 'white',
        borderWidth: 1,
        fontSize: 25,
        color: 'white',
        textAlign: 'center',
        paddingVertical: 10,
        marginVertical: 10,
    },
    formTextLinkRight: {
        color: 'gray',
        fontSize: 15,
        textAlign: 'right',
        width: '80%',
        marginVertical: 10,
    },
    formTextLinkCenter: {
        color: 'gray',
        fontSize: 16,
    },
    formHead2: {
        fontSize: 20,
        color: 'black',
        textAlign: 'center',
        fontWeight: 500,
        // backgroundColor: 'white',
    },
    formHead3: {
        fontSize: 20,
        // backgroundColor: 'white',
        color: '#696969',
        textAlign: 'center',
        fontWeight: 500,
        padding: 10,
        borderRadius: 10,
        width: '80%',
    },
    formHead4: {
        fontSize: 20,
        color: 'black',
        textAlign: 'center',
        fontWeight: 500,
        // backgroundColor: 'white',
    },
    formHead5: {
        fontSize: 20,
        color: 'black',
        textAlign: 'center',
        fontWeight: 'bold',
        marginTop: 30
        // backgroundColor: 'white',
    },
}